name: "Setup the node and R version"

inputs:
    node-version:
        description: "The node version to use"
        required: false
        default: "18.15.x"
    r-version:
        description: "The R version to use"
        required: false
        default: "4.2.3"


runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup R
      if: ${{ inputs.r-version != '' }}
      uses: r-lib/actions/setup-r@v2
      with:
        update-rtools: true
        r-version: ${{ inputs.r-version  }}

    - name: Set site library path (from the rlib-action)
      run: |
        # Set site library path
        cat("::group::Set site library path\n")
        if (Sys.getenv("RENV_PROJECT") != "") {
          message("renv project detected, no need to set R_LIBS_SITE")
          cat(sprintf("R_LIB_FOR_PAK=%s\n", .libPaths()[1]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          q("no")
        }
        lib <- Sys.getenv("R_LIBS_SITE")
        if (lib == "") {
          lib <- file.path(dirname(.Library), "site-library")
          cat(sprintf("R_LIBS_SITE=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          cat(sprintf("R_LIB_FOR_PAK=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          message("Setting R_LIBS_SITE to ", lib)
        } else {
          message("R_LIBS_SITE is already set to ", lib)
          cat(sprintf("R_LIB_FOR_PAK=%s\n", strsplit(lib, .Platform$path.sep)[[1]][[1]]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
        cat("::endgroup::\n")
      shell: Rscript {0}

