name: Check for Broken Links and Publish Wiki

'on':
  push:
    paths:
      - '**/*.md'
      - 'wiki/**'
  pull_request:
    types: [ opened ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # every monday at night
    - cron: '0 1 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup the Environment"
        uses: Code-Inspect/flowr/.github/actions/setup@main

      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          lfs:        true
          submodules: true

      - name: "Checkout LFS"
        run: git lfs checkout

      - name: Update the Capabilities Wiki Page
        run: |
          npm ci
          cp wiki/Capabilities-New.md wiki/Capabilities-Old.md 
          npm run capabilities-markdown --silent > wiki/Capabilities-New.md
          # test if the file changed
          if ! cmp -s wiki/Capabilities-Old.md wiki/Capabilities-New.md; then
              echo "Capabilities changed!"
              echo "CHANGED=true" >> $GITHUB_ENV
              git add -f wiki/Capabilities-New.md
              git commit -m "[skip ci] doc: update capabilities"
          else
              echo "Capabilities did not change!"
          fi
          # delete the old capabilities again
          rm wiki/Capabilities-Old.md

      - name: Push changed capabilities
        if: ${{ env.CHANGED == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.RELEASE_TOKEN }}
          force: true

      - name: Check the README for broken links
        uses: becheran/mlc@v0.16.3
        with:
          args: README.md

      - name: Publish the Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        # we do not need to republish if nothing changes furthermore, do not publish on PR as this should be done by the push on main!
        if: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && !failure() }}
        with:
          path: "wiki/"
          token: ${{ secrets.GH_DEPLOY_WIKI }}

      - name: Check the Wiki pages for broken links
        uses: becheran/mlc@v0.16.3
        if: ${{ always() && !failure() }}
        with:
          args: wiki/
