name: "Full QA"
# Runs only on pull requests to the main branch and on manual triggers

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: "Linting"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@${{ github.ref }}
    with:
      r-version: ''
      action:    lint

  test-full:
      name: "Test suite (full)"
      uses: Code-Inspect/flowr/.github/workflows/run.yaml@${{ github.ref }}
      with:
        action: test-full
        coverage: true

  test-others:
    needs: [ 'lint', 'test-full' ]
    strategy:
      fail-fast: false
      matrix:
        # currently we offer no official support for 3.x TODO: currently  '4.0.5' fails, as we can not detect that there is no pipe!
        r-version: [ '4.1.0' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: "Test Suite (full)"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@${{ github.ref }}
    with:
      r-version: ${{ matrix.r-version }}
      image: ${{ matrix.os }}
      action: test-full
      coverage: true
