name: "Lightweight QA"
# Runs on each push and tests flowR for the default configuration

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
  workflow_dispatch:

jobs:

  lint:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'main' }}
    name: "Linting"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
    with:
      r-version: ''
      action:    lint

  test:
      if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'main' }}
      name: "Test suite (default)"
      uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
      with:
        action: test
        coverage: true
