name: "Lightweight QA"
# Runs on each push and tests flowR for the default configuration

on: [push, workflow_dispatch]

jobs:

  lint:
    name: "Eslint on flowR (default configuration)"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
    with:
      action: lint

  test:
      name: "The (small) test suite"
      uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
      with:
        action: test
        coverage: true
