name: "Lightweight QA"
# Runs on each push and tests flowR for the default configuration

on: [push, workflow_dispatch]

jobs:

  lint:
    name: "Linting"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
    with:
      r-version: ''
      action:    lint

  test:
      name: "Test suite (default)"
      uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
      with:
        action: test
        coverage: true
