name: "Lightweight QA"
# Runs on each push and tests flowR for the default configuration

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  debug:
    needs: [ cleanup ]
    runs-on: ubuntu-latest
    steps:
    - name: "Debug state"
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Base Ref: ${{ github.base_ref }}"

  lint:
    needs: [ debug ]
    if: ${{ github.event_name != 'pull_request' || github.base_ref != 'main' }}
    name: "Linting"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@${{ github.ref }}
    with:
      r-version: ''
      action:    lint

  test:
    needs: [ debug ]
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'main' }}
    name: "Test Suite (default)"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@${{ github.ref }}
    with:
      action: test
      coverage: true
