name: "Lightweight QA"
# Runs on each push and tests flowR for the default configuration

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: "Debug state"
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Base Ref: ${{ github.base_ref }}"

  lint:
    needs: [ debug ]
    name: "Linting"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
    with:
      r-version: ''
      action:    lint

  test:
    needs: [ debug ]
    name: "Test Suite (full)"
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@145-improve-ci
    with:
      action: test-full
      coverage: true
