name: "Run eslint on flowR for a specific version"

'on':
  workflow_call:
    inputs:
      node-version:
        description: "The node version to use"
        required: false
        default: "18.15.x"
        type: string
      r-version:
        description: "The R version to use"
        required: false
        default: "4.2.3"
        type: string


jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Setup the Environment"
        uses: Code-Inspect/flowr/.github/actions/setup@145-improve-ci
        with:
          node-version: ${{ inputs.node-version }}
          r-version: ${{ inputs.r-version }}

      - name: Install Node Dependencies
        run: npm ci

      - name: "Run the linter"
        run:
          npx eslint {src,test}
