name: Publish Wiki Pages

'on':
  push:
    paths:
      - 'wiki/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload the Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki/"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_DEPLOY_WIKI }}
