name: "QA"
# Runs on each push and tests flowR for the default configuration
# Depending on the targets etc. this may perform many more checks!

'on':
  push:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'scripts/**'
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force-full:
        description: "Force all steps"
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  deployments: write
  contents:    write

jobs:
  debug:
    name: "Debug"
    runs-on: ubuntu-latest
    steps:
    - name: "Debug state"
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Base Ref: ${{ github.base_ref }}"

  lint:
    needs: [ debug ]
    name: "Linting"
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'main' }}
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@main
    with:
      r-version: ''
      action:    lint

  test:
    needs: [ debug ]
    name: "Test Suite (coverage)"
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.ref != 'main' }}
    uses: Code-Inspect/flowr/.github/workflows/run.yaml@main
    with:
      action: test-full
      coverage: true


  performance-test:
    needs: [ test ]
    name: "Run Performance Tests (only on main)"
    # TODO: if everything works: && (inputs.force-full || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    if: ${{ always() && !failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Inspect/flowr/.github/workflows/run.yaml@161-setup-an-automatic-and-reproducible-performance-benchmark-with-the-ci
        with:
          action: performance-test
          coverage: false
          benchmark: true
          timeout-minutes: 25

      - name: Download previous benchmark data
        id: restore-benchmark-cache
        uses: actions/cache@v3.3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: "Upload Performance Results"
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Artificial Benchmark Suite'
          tool: 'customSmallerIsBetter'
          output-file-path: ./test/performance/results/artificial/artificial-graph.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          summary-always: true
          skip-fetch-gh-pages: true

      - name: Update previous benchmark data
        uses: actions/cache/save@v3.3
        with:
          path: ./cache
          key: ${{ steps.restore-benchmark-cache.outputs.cache-primary-key }}


  full-test:
    needs: [ lint ]
    name: "Run Full Test Suite (only on PR to main)"
    if: ${{ always() && !failure() && (inputs.force-full || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main')) }}
    uses: Code-Inspect/flowr/.github/workflows/full-test.yaml@main

  deploy-doc:
    needs: [ test, full-test ]
    name: "Deploy Documentation (only on main)"
    if: ${{ always() && !failure() && (inputs.force-full || (github.event_name == 'push' && github.ref == 'refs/heads/main')) }}
    uses: Code-Inspect/flowr/.github/workflows/deploy-doc.yaml@main
