name: "Release"

'on':
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[release:')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm run release

  deploy-docker:
    needs: [ release ]
    name: "Deploy Docker (only on main)"
    if: startsWith(github.event.head_commit.message, '[release:')
    uses: Code-Inspect/flowr/.github/workflows/deploy-docker.yaml@main
    secrets: inherit
