name: "Run one of flowR's npm-actions with a specific version"

'on':
  workflow_call:
    inputs:
      node-version:
        description: "The node version to use"
        required: false
        default: "18.15.x"
        type: string
      r-version:
        description: "The R version to use"
        required: false
        default: "4.2.3"
        type: string
      action:
        description: "The action to run"
        required: true
        type: string
      image:
        description: "The image to use for running"
        required: false
        default: "ubuntu-22.04"
        type: string
      timeout-minutes:
        description: "The timeout in minutes"
        required: false
        default: 10
        type: number
      coverage:
        description: "Whether to upload coverage reports at the end"
        required: false
        default: false
        type: boolean
      benchmark:
        description: "Name to use to report and upload benchmark results at the end"
        required: false
        default: ''
        type: string


jobs:
  flowr-action:
    runs-on: ${{ inputs.image }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: "Setup the Environment"
        uses: Code-Inspect/flowr/.github/actions/setup@main
        with:
          node-version: ${{ inputs.node-version }}
          r-version: ${{ inputs.r-version }}

      - name: Install Node Dependencies
        run: npm ci

      - name: "Run the corresponding action '${{ inputs.action }}'"
        run:
          npm run ${{ inputs.action }}

      - name: Upload Coverage Reports to Codecov
        if: ${{ inputs.coverage }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Commit New Documentation
        if: ${{ inputs.action == 'doc' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "doc/"
          git commit -m "Update documentation"

      - name: Push New Documentation
        if: ${{ inputs.action == 'doc' }}
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: Upload Coverage Reports to Codecov
        if: ${{ inputs.benchmark != "" }}
        uses: actions/upload-artifact@v3.1.3
        with:
            name: benchmark-results-${{ inputs.benchmark }}
            path: test/performance/results/
