name: "Run one of flowR's npm-actions with a specific version"

'on':
  workflow_call:
    inputs:
      node-version:
        description: "The node version to use"
        required: false
        default: "18.15.x"
        type: string
      r-version:
        description: "The R version to use"
        required: false
        default: "4.2.3"
        type: string
      action:
        description: "The action to run"
        required: true
        type: string
      coverage:
        description: "Whether to upload coverage reports at the end"
        required: false
        default: false
        type: boolean

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Setup the Environment"
        uses: Code-Inspect/flowr/.github/actions/setup@145-improve-ci
        with:
          node-version: ${{ inputs.node-version }}
          r-version: ${{ inputs.r-version }}

      - name: Install Node Dependencies
        run: npm ci

      - name: "Run the corresponding action ${{ inputs.action }}"
        run:
          npm run ${{ inputs.action }}

      - name: Upload Coverage Reports to Codecov
        if: ${{ inputs.coverage }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

