name: Run tests

on:
  - push
  - workflow_dispatch

env:
  NODE_VERSION: '18.15.x'
  R_VERSION: '4.2.3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test